### ISSUE TITLE
change your breakpoint

### ISSUE THREAD

**Issue by mosi3883** [AlexGDevPro/FEM_Ch.-1_Stats-preview-card-component#1]
i think you need change your break point to 800px
or something like that
seeing your website in Desktop HD screen(1366 x 768) and its like mobile. :)

better to use box-sizing:border-box;
but overall code is ok.

**Comment by AlexGDevPro** [comment]
Thanks for your feedback.

I used both sizes requested (375px, and 1440px), but if I push it any further I would probably do a tablet view or a continusly responsive design.
Maybe later.

Thanks

**Comment by AlexGDevPro** [comment]
Done :)

I've made my code more responsive.

Hope you'll find it good.
